[package]
name = "ngide"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
terminal_size = "0.1.17"
console = "0.14.1"
atty = "0.2.14"
libc = "0.2.99"
